name: pocket_fhir
description: Starting point for Pocketbase for FHIR
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  fhir_r5: 
    path: ../../new_fhir/fhir_r5
  pocketbase: ^0.18.1
  riverpod: ^2.5.1
  rxdart: ^0.28.0

dependency_overrides:
  collection: ^1.19.0
  meta: ^1.12.0